version: '3.4'

networks:
  backend:

services:
  piratmessages.db:
    container_name: piratmessages-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend 
    ports:
      - 8001:1433

  piratmessages.webapi:
    container_name: piratmessages-webapi
    image: ${DOCKER_REGISTRY-}piratmessageswebapi
    build:
      context: .
      dockerfile: PiratMessages.WebApi/Dockerfile
    networks:
      - backend
    ports:
      - 8002:80
    environment:
      - DB_HOST=piratmessages.db
      - DB_NAME=piratmessagesdb
      - DB_SA_PASSWORD=password@12345#

  piratmessages.seq:
    container_name: piratmessages-seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    networks:
      - backend
    ports:
      - 5341:5341
      - 8081:80

  piratmessages.messaging:
    container_name: piratmessages-rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - backend
    ports:
      - 15672:15672
      - 5672:5672

  piratmessages.caching:
    container_name: piratmessages-rediscache
    image: redis:latest
    hostname: rediscache
    restart: always
    networks:
      - backend
    ports: 
      - '6379:6379'

